### ISSUE TITLE
Missing module 'custom_layers'

### ISSUE THREAD

**Issue by Guy-Yome** [HackerPoet/FaceEditor#2]
So, yeah. I've been doing all my import homework and somehow seem to be missing some kind of class made by you or not online? I don't know. But it's named 'custom_layers'. Could you explain what is happening? It's at face_edit.py line 68.

**Comment by HackerPoet** [comment]
Sorry, that was my own file that had some experimental layers, but I didn't end up using them in this project and I forgot to remove the import.  You can safely delete it.

**EDIT:** I've updated the master branch to remove them.

**Comment by Guy-Yome** [comment]
Thanks man! :)
